SELECT DISTINCT
STOK.STOCKREF [STOK_ID],
ITM.[NAME] [STOK_ACIKLAMASI],
STOK.INVENNO [DEPO_AMBAR_NO],
AMBAR.[NAME] [DEPO_ADI],
STOK.ONHAND [STOK]
FROM
LV_006_01_GNTOTST STOK WITH(NOLOCK)
LEFT JOIN L_CAPIWHOUSE AMBAR WITH(NOLOCK) ON STOK.INVENNO=AMBAR.NR AND AMBAR.FIRMNR=@FIRMANO
LEFT JOIN LG_006_ITEMS ITM WITH(NOLOCK) ON STOK.STOCKREF=ITM.LOGICALREF
LEFT JOIN LG_006_UNITBARCODE UNITBARCODE WITH(NOLOCK) ON ITM.LOGICALREF=UNITBARCODE.ITEMREF
WHERE
STOK.INVENNO !=-1 --INVENNO=-1 TÜM AMBARLARIN TOPLAM STOÐUNU TUTAR. BÝZ ONUN DIÞINDAKÝ TÜM AMBARLARIN GELMESÝNÝ ÝSTEDÝK.
AND ITM.ACTIVE=0 --AKTÝF MALZEME KARTLARINI GETÝR DEDÝK, 1=PASÝFLERÝ GETÝRÝR
AND ITM.CARDTYPE=1-- MALZEME KART TÝPÝ, MALZEME OLANLARI GETÝR DEDÝK
--AND UNITBARCODE.BARCODE='8699594701053'
AND UNITBARCODE.BARCODE=@BARKOD --ÜRÜN BARKOD ARAMA, BARKODUN TAMAMI OKUTULARAK BULUNMAK ÝSTENÝRSE BU AKTÝF EDÝLMELÝDÝR.
--AND UNITBARCODE.BARCODE LIKE '%'+ @BARKOD + '%' --ÜRÜN BARKOD ARAMA, BARKODUN BÝR KISMINI YAZARAK ÜRÜN BULMA ÝSTENÝRSE BU AKTÝF OLMALIDIR.
--AND ITM.CODE=@STOKKODU --ÜRÜN ARAMA STOK KODUNA GÖRE YAPILACAKSA VE STOK KODUNUN TAMAMI YAZILARAK ÜRÜN BULUNMAK ÝSTENÝYORSA BURASI AKTÝF OLMALIDIR.
--AND ITM.CODE LIKE '%'+ @STOKKODU + '%' --ÜRÜN ARAMA STOK KODUNA GÖRE YAPILACAKSA VE STOK KODUNUN BÝR KISMI YAZILARAK ÜRÜN BULUNMAK ÝSTENÝRSE BURASI AKTÝF OLACAK.
--AND ITM.[NAME] LIKE '%'+ @STOKADI + '%' --ÜRÜN ARAMA STOK ADINA GÖRE YAPILACAKSA VE STOK ARAMA ÜRÜN ADININ BÝR KISMI YAZILARAK BULUNMAK ÝSTENÝRSE BURASI AKTÝF OLACAK.
ORDER BY STOK.STOCKREF,STOK.INVENNO